"""new video group_id column

Revision ID: 3a1718c4a97d
Revises: bfd634c39601
Create Date: 2026-06-01 13:32:14.956684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a1718c4a97d'
down_revision: Union[str, Sequence[str], None] = 'bfd634c39601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('group_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'group_id')
    # ### end Alembic commands ###
