"""Update FK on users to role_number instead of role id

Revision ID: 8f3a41947fc4
Revises: 3e4f99ae1e51
Create Date: 2025-12-02 18:51:13.149949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision: str = '8f3a41947fc4'
down_revision: Union[str, Sequence[str], None] = '3e4f99ae1e51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_number_fk', sa.Integer(), nullable=True))

    op.execute(
        text("UPDATE users SET role_number_fk = 0")
    )

    op.alter_column(
        'users', 'role_number_fk',
        existing_type=sa.INTEGER(),
        nullable=False
    )

    op.drop_constraint(op.f('users_role_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_number_fk'], ['role_number'])
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_role_id_fkey'), 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'role_number_fk')
    # ### end Alembic commands ###
