"""roles table updated to name and number

Revision ID: a990828dca13
Revises: cc144723318b
Create Date: 2025-10-28 18:43:47.646940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a990828dca13'
down_revision: Union[str, Sequence[str], None] = 'cc144723318b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('role_number', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_role_number'), 'roles', ['role_number'], unique=True)
    op.drop_column('roles', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_roles_role_number'), table_name='roles')
    op.drop_column('roles', 'role_number')
    # ### end Alembic commands ###
